import { useState, useRef } from 'react';
import { useNavigate } from 'react-router-dom';
import AudioGenerateButton from '../../components/AudioGenerateButton';

const BASE = import.meta.env.VITE_API_BASE || '/api';

async function apiFetch(path, options = {}) {
  const token = localStorage.getItem('wenjing_token');
  const headers = { ...options.headers };
  if (!(options.body instanceof FormData)) headers['Content-Type'] = 'application/json';
  if (token) headers['Authorization'] = `Bearer ${token}`;
  const res = await fetch(`${BASE}${path}`, { ...options, headers });
  const data = await res.json().catch(() => ({}));
  if (!res.ok) throw new Error(data.error || `Request failed (${res.status})`);
  return data;
}

function Field({ label, value, onChange, rows = 4, mono = false }) {
  return (
    <div style={{ marginBottom: 20 }}>
      {label && <label style={{ display: 'block', fontSize: 12, fontWeight: 600, color: 'var(--text-muted)', textTransform: 'uppercase', letterSpacing: '0.05em', marginBottom: 6 }}>{label}</label>}
      <textarea
        value={value || ''}
        onChange={e => onChange(e.target.value)}
        rows={rows}
        style={{ width: '100%', padding: '10px 12px', border: '1px solid var(--border)', borderRadius: 6, fontSize: mono ? 13 : 14, fontFamily: mono ? 'monospace' : 'inherit', lineHeight: 1.7, resize: 'vertical', boxSizing: 'border-box', color: 'var(--text)' }}
      />
    </div>
  );
}

export default function AdminPDFUpload() {
  const navigate = useNavigate();
  const fileInputRef = useRef(null);
  const htmlInputRef = useRef(null);
  const [file, setFile] = useState(null);
  const [parsing, setParsing] = useState(false);
  const [extractingHtml, setExtractingHtml] = useState(false);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState('');
  const [content, setContent] = useState(null);

  function setField(key, val) {
    setContent(c => ({ ...c, [key]: val }));
  }

  async function handleFile(f) {
    if (!f || f.type !== 'application/pdf') { setError('Please select a PDF file'); return; }
    setFile(f);
    setError('');
    setParsing(true);
    setContent(null);
    try {
      const form = new FormData();
      form.append('pdf', f);
      const data = await apiFetch('/admin/parse-pdf-post', { method: 'POST', body: form });
      setContent(data);
    } catch (err) {
      setError('Failed to parse PDF: ' + err.message);
    }
    setParsing(false);
  }

  // Upload an HTML file to extract the original English article text
  async function handleHtmlUpload(f) {
    if (!f) return;
    const ext = f.name.split('.').pop().toLowerCase();
    if (ext !== 'html' && ext !== 'htm') { setError('Please select an HTML file (.html)'); return; }
    setExtractingHtml(true);
    setError('');
    try {
      const form = new FormData();
      form.append('pdf', f); // server uses upload.single('pdf') for this route
      const data = await apiFetch('/admin/generate', { method: 'POST', body: form });
      // Only take the pdf_text from the HTML extraction, keep everything else from the PDF
      setField('pdf_text', data.pdf_text || '');
      // Also prefill economist_title if still empty
      if (!content?.economist_title && data.economist_title) {
        setField('economist_title', data.economist_title);
      }
    } catch (err) {
      setError('Failed to extract article from HTML: ' + err.message);
    }
    setExtractingHtml(false);
  }

  async function handleSave(isPublished) {
    setSaving(true);
    setError('');
    try {
      const payload = { ...content, is_published: isPublished };
      if (isPublished && !payload.published_at) {
        payload.published_at = new Date().toISOString();
      } else if (payload.published_at && !payload.published_at.includes('T')) {
        payload.published_at = new Date(payload.published_at + 'T12:00:00').toISOString();
      }
      await apiFetch('/admin/posts', { method: 'POST', body: JSON.stringify(payload) });
      navigate('/admin/posts');
    } catch (err) {
      setError('Save failed: ' + err.message);
    }
    setSaving(false);
  }

  const missingArticle = content && !content.pdf_text;

  return (
    <div style={{ maxWidth: 800 }}>
      <div style={{ marginBottom: 28 }}>
        <h2 style={{ fontFamily: 'var(--serif)', fontSize: 22, marginBottom: 6 }}>Upload PDF</h2>
        <p style={{ fontSize: 14, color: 'var(--text-muted)' }}>
          Upload a PDF in the standard analysis format. Sections will be extracted automatically — any missing sections will be generated by AI.
        </p>
      </div>

      {/* Upload zone */}
      {!content && (
        <div
          onClick={() => fileInputRef.current?.click()}
          onDrop={e => { e.preventDefault(); handleFile(e.dataTransfer.files[0]); }}
          onDragOver={e => e.preventDefault()}
          style={{ border: '2px dashed var(--border)', borderRadius: 10, padding: '48px 32px', textAlign: 'center', cursor: 'pointer', marginBottom: 24, background: 'white', transition: 'border-color 0.15s' }}
          onMouseEnter={e => e.currentTarget.style.borderColor = '#CC0000'}
          onMouseLeave={e => e.currentTarget.style.borderColor = 'var(--border)'}
        >
          <input ref={fileInputRef} type="file" accept=".pdf" style={{ display: 'none' }} onChange={e => handleFile(e.target.files[0])} />
          {parsing ? (
            <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 12 }}>
              <div className="spinner" style={{ width: 28, height: 28 }} />
              <span style={{ fontSize: 14, color: 'var(--text-muted)' }}>Parsing PDF and extracting sections…</span>
            </div>
          ) : (
            <>
              <div style={{ fontSize: 32, marginBottom: 12, opacity: 0.3 }}>PDF</div>
              <div style={{ fontWeight: 500, marginBottom: 6 }}>{file ? file.name : 'Click to upload PDF, or drag and drop'}</div>
              <div style={{ fontSize: 13, color: 'var(--text-muted)' }}>Format: 经济学人｜MMDD｜Article title</div>
            </>
          )}
        </div>
      )}

      {error && <div className="error-msg" style={{ marginBottom: 16 }}>{error}</div>}

      {content && (
        <div>
          <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: 24, background: '#F0FFF4', border: '1px solid #C6F6D5', borderRadius: 8, padding: '12px 16px' }}>
            <span style={{ fontSize: 14, color: '#276749' }}>PDF parsed. Review and edit before publishing.</span>
            <button onClick={() => { setContent(null); setFile(null); }} style={{ background: 'none', border: 'none', cursor: 'pointer', fontSize: 13, color: '#276749', textDecoration: 'underline' }}>
              Upload different PDF
            </button>
          </div>

          {/* Article Info */}
          <div style={{ background: 'white', border: '1px solid var(--border)', borderRadius: 8, padding: '20px 24px', marginBottom: 20 }}>
            <h3 style={{ fontSize: 15, fontWeight: 700, marginBottom: 16 }}>Article Info</h3>
            <div style={{ marginBottom: 16 }}>
              <label style={{ display: 'block', fontSize: 12, fontWeight: 600, color: 'var(--text-muted)', textTransform: 'uppercase', letterSpacing: '0.05em', marginBottom: 6 }}>Chinese Title</label>
              <input value={content.title || ''} onChange={e => setField('title', e.target.value)}
                style={{ width: '100%', padding: '10px 12px', border: '1px solid var(--border)', borderRadius: 6, fontSize: 15, boxSizing: 'border-box' }} />
            </div>
            <div style={{ marginBottom: 16 }}>
              <label style={{ display: 'block', fontSize: 12, fontWeight: 600, color: 'var(--text-muted)', textTransform: 'uppercase', letterSpacing: '0.05em', marginBottom: 6 }}>Original English Title</label>
              <input value={content.economist_title || ''} onChange={e => setField('economist_title', e.target.value)}
                style={{ width: '100%', padding: '10px 12px', border: '1px solid var(--border)', borderRadius: 6, fontSize: 14, boxSizing: 'border-box' }} />
            </div>
            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 16 }}>
              <div>
                <label style={{ display: 'block', fontSize: 12, fontWeight: 600, color: 'var(--text-muted)', textTransform: 'uppercase', letterSpacing: '0.05em', marginBottom: 6 }}>Published Date</label>
                <input type="date" value={content.published_at || ''} onChange={e => setField('published_at', e.target.value)}
                  style={{ width: '100%', padding: '10px 12px', border: '1px solid var(--border)', borderRadius: 6, fontSize: 14, boxSizing: 'border-box' }} />
              </div>
              <div>
                <label style={{ display: 'block', fontSize: 12, fontWeight: 600, color: 'var(--text-muted)', textTransform: 'uppercase', letterSpacing: '0.05em', marginBottom: 6 }}>Country Tags (comma separated)</label>
                <input
                  value={Array.isArray(content.country_tags) ? content.country_tags.join(', ') : ''}
                  onChange={e => setField('country_tags', e.target.value.split(',').map(t => t.trim()).filter(Boolean))}
                  placeholder="China, Iran, United States"
                  style={{ width: '100%', padding: '10px 12px', border: '1px solid var(--border)', borderRadius: 6, fontSize: 14, boxSizing: 'border-box' }} />
              </div>
            </div>
          </div>

          {/* Content Sections */}
          <div style={{ background: 'white', border: '1px solid var(--border)', borderRadius: 8, padding: '20px 24px', marginBottom: 20 }}>
            <h3 style={{ fontSize: 15, fontWeight: 700, marginBottom: 16 }}>Content Sections</h3>
            <Field label="Summary (一句话总结)" value={content.summary} onChange={v => setField('summary', v)} rows={2} />
            <Field label="Audio Script (语音稿)" value={content.audio_script} onChange={v => setField('audio_script', v)} rows={6} />
            <AudioGenerateButton script={content.audio_script} onAudioGenerated={url => setField('audio_url', url)} />
            <Field label="More Insights (深度分析)" value={content.theory_explanation} onChange={v => setField('theory_explanation', v)} rows={8} />
            <Field label="Exam Questions (启发性问题)" value={content.exam_questions} onChange={v => setField('exam_questions', v)} rows={8} />
            <Field label="Other Media Perspectives (外媒视角)" value={content.other_media} onChange={v => setField('other_media', v)} rows={8} />
          </div>

          {/* Original Article */}
          <div style={{ background: 'white', border: '1px solid var(--border)', borderRadius: 8, padding: '20px 24px', marginBottom: 24 }}>
            <div style={{ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', marginBottom: 8, gap: 16 }}>
              <div>
                <h3 style={{ fontSize: 15, fontWeight: 700, marginBottom: 4 }}>Original Article (English)</h3>
                <p style={{ fontSize: 13, color: 'var(--text-muted)' }}>This will appear in the Learn English section.</p>
              </div>
            </div>

            {/* Show HTML upload prompt if no article text */}
            {missingArticle && (
              <div style={{ background: '#FFFBEB', border: '1px solid #F6E05E', borderRadius: 8, padding: '16px', marginBottom: 16 }}>
                <div style={{ fontWeight: 600, fontSize: 14, color: '#744210', marginBottom: 6 }}>
                  No original article found in PDF
                </div>
                <p style={{ fontSize: 13, color: '#92400E', marginBottom: 12, lineHeight: 1.6 }}>
                  To add the English article for the Learn English section, save the article page from The Economist website as HTML (File → Save Page As → "Webpage, HTML Only") and upload it here.
                </p>
                <input ref={htmlInputRef} type="file" accept=".html,.htm" style={{ display: 'none' }}
                  onChange={e => handleHtmlUpload(e.target.files[0])} />
                <button
                  onClick={() => htmlInputRef.current?.click()}
                  disabled={extractingHtml}
                  style={{ padding: '8px 16px', background: '#CC0000', color: 'white', border: 'none', borderRadius: 6, cursor: extractingHtml ? 'not-allowed' : 'pointer', fontSize: 13, fontWeight: 500, display: 'flex', alignItems: 'center', gap: 8 }}
                >
                  {extractingHtml && <span style={{ width: 12, height: 12, border: '2px solid rgba(255,255,255,0.4)', borderTopColor: 'white', borderRadius: '50%', display: 'inline-block', animation: 'spin 0.8s linear infinite' }} />}
                  {extractingHtml ? 'Extracting article…' : 'Upload article HTML'}
                </button>
                <p style={{ fontSize: 12, color: '#92400E', marginTop: 8 }}>
                  You can also skip this and publish without the English article.
                </p>
              </div>
            )}

            <Field label="" value={content.pdf_text} onChange={v => setField('pdf_text', v)} rows={12} mono />

            {/* If article was just added via HTML, show success */}
            {!missingArticle && content.pdf_text && (
              <div style={{ marginTop: 4 }}>
                <button
                  onClick={() => htmlInputRef.current?.click()}
                  disabled={extractingHtml}
                  style={{ fontSize: 12, color: 'var(--text-muted)', background: 'none', border: 'none', cursor: 'pointer', textDecoration: 'underline', padding: 0 }}
                >
                  {extractingHtml ? 'Extracting…' : 'Re-upload HTML to replace article text'}
                </button>
                <input ref={htmlInputRef} type="file" accept=".html,.htm" style={{ display: 'none' }}
                  onChange={e => handleHtmlUpload(e.target.files[0])} />
              </div>
            )}
          </div>

          {/* Actions */}
          <div style={{ display: 'flex', gap: 12, justifyContent: 'flex-end' }}>
            <button onClick={() => handleSave(false)} disabled={saving} className="btn btn-outline">Save as Draft</button>
            <button onClick={() => handleSave(true)} disabled={saving} className="btn btn-primary">
              {saving ? 'Publishing…' : 'Publish'}
            </button>
          </div>
        </div>
      )}
    </div>
  );
}